In [119]:
import pandas as pd
import numpy as np
import json, os
import os

In [120]:
PATH = 'C:/apps/analysis/election/'
df_1976 = pd.read_csv(PATH + "1976.csv", encoding='utf-8-sig')
df_1980 = pd.read_csv(PATH + "1980.csv", encoding='utf-8-sig')
df_1984 = pd.read_csv(PATH + "1984.csv", encoding='utf-8-sig')
df_1988 = pd.read_csv(PATH + "1988.csv", encoding='utf-8-sig')
df_1992 = pd.read_csv(PATH + "1992.csv", encoding='utf-8-sig')
df_1996 = pd.read_csv(PATH + "1996.csv", encoding='utf-8-sig')
df_2000 = pd.read_csv(PATH + "2000.csv", encoding='utf-8-sig')
df_2004 = pd.read_csv(PATH + "2004.csv", encoding='utf-8-sig')
df_2008 = pd.read_csv(PATH + "2008.csv", encoding='utf-8-sig')
df_2012 = pd.read_csv(PATH + "2012.csv", encoding='utf-8-sig')
df_2016 = pd.read_csv(PATH + "2016.csv", encoding='utf-8-sig')
df_2020 = pd.read_csv(PATH + "2020.csv", encoding='utf-8-sig')

In [121]:
df_1976.drop('notes', axis=1)
df_1976 = df_1976.drop('writein', axis=1)
df_1976 = df_1976[['party_simplified', 'candidatevotes']]
df_1976 = df_1976.groupby(df_1976['party_simplified']).sum()
data = pd.read_csv(PATH + "1976.csv", encoding='utf-8-sig')
date_column = data['year'][0]
df_1976.columns = [date_column]
df_1976

                      1976
party_simplified
DEMOCRAT          40680446
LIBERTARIAN          95626
OTHER              1954379
REPUBLICAN        38870893

In [122]:
df_1980.drop('notes', axis=1)
df_1980 = df_1980.drop('writein', axis=1)
df_1980 = df_1980[['party_simplified', 'candidatevotes']]
df_1980 = df_1980.groupby(df_1980['party_simplified']).sum()
data = pd.read_csv(PATH + "1980.csv", encoding='utf-8-sig')
date_column = data['year'][0]
df_1980.columns = [date_column]
df_1980

                      1980
party_simplified
DEMOCRAT          35480948
LIBERTARIAN         867401
OTHER              6505863
REPUBLICAN        43642639

In [123]:
df_1984.drop('notes', axis=1)
df_1984 = df_1984.drop('writein', axis=1)
df_1984 = df_1984[['party_simplified', 'candidatevotes']]
df_1984 = df_1984.groupby(df_1984['party_simplified']).sum()
data = pd.read_csv(PATH + "1984.csv", encoding='utf-8-sig')
date_column = data['year'][0]
df_1984.columns = [date_column]
df_1984

                      1984
party_simplified
DEMOCRAT          37449813
LIBERTARIAN         227204
OTHER               811015
REPUBLICAN        54166829

In [124]:
df_1988.drop('notes', axis=1)
df_1988 = df_1988.drop('writein', axis=1)
df_1988 = df_1988[['party_simplified', 'candidatevotes']]
df_1988 = df_1988.groupby(df_1988['party_simplified']).sum()
data = pd.read_csv(PATH + "1988.csv", encoding='utf-8-sig')
date_column = data['year'][0]
df_1988.columns = [date_column]
df_1988

                      1988
party_simplified
DEMOCRAT          41716679
LIBERTARIAN         409708
OTHER               817798
REPUBLICAN        48642640

In [125]:
df_1992.drop('notes', axis=1)
df_1992 = df_1992.drop('writein', axis=1)
df_1992 = df_1992[['party_simplified', 'candidatevotes']]
df_1992 = df_1992.groupby(df_1992['party_simplified']).sum()
data = pd.read_csv(PATH + "1992.csv", encoding='utf-8-sig')
date_column = data['year'][0]
df_1992.columns = [date_column]
df_1992

                      1992
party_simplified
DEMOCRAT          44856747
LIBERTARIAN         280848
OTHER             20663272
REPUBLICAN        38798913

In [126]:
df_1996.drop('notes', axis=1)
df_1996 = df_1996.drop('writein', axis=1)
df_1996 = df_1996[['party_simplified', 'candidatevotes']]
df_1996 = df_1996.groupby(df_1996['party_simplified']).sum()
data = pd.read_csv(PATH + "1996.csv", encoding='utf-8-sig')
date_column = data['year'][0]
df_1996.columns = [date_column]
df_1996

                      1996
party_simplified
DEMOCRAT          47295351
LIBERTARIAN         465351
OTHER              9625419
REPUBLICAN        39003697

In [127]:
df_2000.drop('notes', axis=1)
df_2000 = df_2000.drop('writein', axis=1)
df_2000 = df_2000[['party_simplified', 'candidatevotes']]
df_2000 = df_2000.groupby(df_2000['party_simplified']).sum()
data = pd.read_csv(PATH + "2000.csv", encoding='utf-8-sig')
date_column = data['year'][0]
df_2000.columns = [date_column]
df_2000

                      2000
party_simplified
DEMOCRAT          50830580
LIBERTARIAN         380405
OTHER              4071625
REPUBLICAN        50311372

In [128]:
df_2004.drop('notes', axis=1)
df_2004 = df_2004.drop('writein', axis=1)
df_2004 = df_2004[['party_simplified', 'candidatevotes']]
df_2004 = df_2004.groupby(df_2004['party_simplified']).sum()
data = pd.read_csv(PATH + "2004.csv", encoding='utf-8-sig')
date_column = data['year'][0]
df_2004.columns = [date_column]
df_2004

                      2004
party_simplified
DEMOCRAT          58894561
LIBERTARIAN         369308
OTHER              1212870
REPUBLICAN        61872711

In [129]:
df_2008.drop('notes', axis=1)
df_2008 = df_2008.drop('writein', axis=1)
df_2008 = df_2008[['party_simplified', 'candidatevotes']]
df_2008 = df_2008.groupby(df_2008['party_simplified']).sum()
data = pd.read_csv(PATH + "2008.csv", encoding='utf-8-sig')
date_column = data['year'][0]
df_2008.columns = [date_column]
df_2008

                      2008
party_simplified
DEMOCRAT          69338846
LIBERTARIAN         510456
OTHER              1956116
REPUBLICAN        59613835

In [130]:
df_2012.drop('notes', axis=1)
df_2012 = df_2012.drop('writein', axis=1)
df_2012 = df_2012[['party_simplified', 'candidatevotes']]
df_2012 = df_2012.groupby(df_2012['party_simplified']).sum()
data = pd.read_csv(PATH + "2012.csv", encoding='utf-8-sig')
date_column = data['year'][0]
df_2012.columns = [date_column]
df_2012

                      2012
party_simplified
DEMOCRAT          65752017
LIBERTARIAN        1216400
OTHER              1501463
REPUBLICAN        60670117

In [131]:
df_2016.drop('notes', axis=1)
df_2016 = df_2016.drop('writein', axis=1)
df_2016 = df_2016[['party_simplified', 'candidatevotes']]
df_2016 = df_2016.groupby(df_2016['party_simplified']).sum()
data = pd.read_csv(PATH + "2016.csv", encoding='utf-8-sig')
date_column = data['year'][0]
df_2016.columns = [date_column]
df_2016

                      2016
party_simplified
DEMOCRAT          65677288
LIBERTARIAN        4125170
OTHER              4292059
REPUBLICAN        62692670

In [132]:
df_2020.drop('notes', axis=1)
df_2020 = df_2020.drop('writein', axis=1)
df_2020 = df_2020[['party_simplified', 'candidatevotes']]
df_2020 = df_2020.groupby(df_2020['party_simplified']).sum()
data = pd.read_csv(PATH + "2020.csv", encoding='utf-8-sig')
date_column = data['year'][0]
df_2020.columns = [date_column]
df_2020

                      2020
party_simplified
DEMOCRAT          81268908
LIBERTARIAN        1797355
OTHER              1246094
REPUBLICAN        74216146

In [133]:
from functools import reduce
dfs = [df_1976, df_1980, df_1984, df_1988, df_1992, df_1996, df_2000, df_2004, df_2008, df_2012, df_2016, df_2020]
df_final = reduce(lambda left, right: pd.merge(left, right, how = 'left', on='party_simplified'), dfs)

In [134]:
df_final

,1976,1980,1984,1988,1992,1996,2000,2004,2008,2012,2016,2020
party_simplified,,,,,,,,,,,,
DEMOCRAT,40680446,35480948,37449813,41716679,44856747,47295351,50830580,58894561,69338846,65752017,65677288,81268908
LIBERTARIAN,95626,867401,227204,409708,280848,465351,380405,369308,510456,1216400,4125170,1797355
OTHER,1954379,6505863,811015,817798,20663272,9625419,4071625,1212870,1956116,1501463,4292059,1246094
REPUBLICAN,38870893,43642639,54166829,48642640,38798913,39003697,50311372,61872711,59613835,60670117,62692670,74216146

In [135]:
df_final.to_csv("party_election_graph.csv")